# Generated by Django 2.2.2 on 2020-03-01 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('1', '男'), ('0', '女')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card', models.CharField(max_length=18)),
                ('per', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booktest.Person')),
            ],
        ),
    ]
