# Generated by Django 2.2.2 on 2020-03-01 16:06

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0004_temp'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='temp',
            managers=[
                ('myobjects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='pub_date',
            field=models.DateTimeField(),
        ),
    ]
