# Generated by Django 2.2.2 on 2020-03-01 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0006_areainfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areainfo',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booktest.AreaInfo'),
        ),
    ]
