# Generated by Django 2.2.2 on 2020-03-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_messageinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageinfo',
            name='subject',
            field=models.CharField(blank=True, max_length=20, null=None),
        ),
        migrations.AddField(
            model_name='messageinfo',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=None),
        ),
        migrations.AlterField(
            model_name='messageinfo',
            name='email',
            field=models.CharField(blank=True, max_length=20, null=None),
        ),
    ]
